In [2]:
!pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 12.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=fd51730d718e5a983b5095100cf66ad0c3bbc7c296a28286497d1df14f736dc8
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [2]:
import os
import csv
import re
import sys
import spacy
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from langdetect import detect
import pickle
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.tag import pos_tag
from nltk.probability import FreqDist

import pickle

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [1]:
import sklearn
import numpy
import scipy

print("sklearn:", sklearn.__version__)
print("numpy:", numpy.__version__)
print("scipy:", scipy.__version__)

sklearn: 1.6.1
numpy: 2.0.2
scipy: 1.16.3

In [3]:
nltk.download("stopwords")
nltk.download("punkt")
nltk.download("names")
nltk.download("wordnet")
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('tagsets')
nltk.download('tagsets_json')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package names to /root/nltk_data...
[nltk_data]   Unzipping corpora/names.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Unzipping help/tagsets.zip.
[nltk_data] Downloading package tagsets_json to /root/nltk_data...
[nltk_data]   Unzipping help/tagsets_json.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [4]:
STOPWORDS = nltk.corpus.stopwords.words("english")
NAMES = nltk.corpus.names.words()

In [72]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

True

In [6]:
csv.field_size_limit(sys.maxsize)

df = pd.read_csv(
    "/content/drive/MyDrive/NLP1/Phishing.csv",
    engine="python"
)

In [7]:
df.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [8]:
df.drop(columns="Unnamed: 0",inplace=True)

In [9]:
df.columns

Index(['Email Text', 'Email Type'], dtype='object')

In [10]:
df['Email Text'].astype(str)

0        re : 6 . 1100 , disc : uniformitarianism , re ...
1        the other side of * galicismos * * galicismo *...
2        re : equistar deal tickets are you still avail...
3        \nHello I am your hot lil horny toy.\n    I am...
4        software at incredibly low prices ( 86 % lower...
                               ...
18645    date a lonely housewife always wanted to date ...
18646    request submitted : access request for anita ....
18647    re : important - prc mtg hi dorn & john , as y...
18648    press clippings - letter on californian utilit...
18649                                                empty
Name: Email Text, Length: 18650, dtype: object

In [11]:
df['Email Text'].loc[3]

'\nHello I am your hot lil horny toy.\n    I am the one you dream About,\n    I am a very open minded person,\n    Love to talk about and any subject.\n    Fantasy is my way of life, \n    Ultimate in sex play.     Ummmmmmmmmmmmmm\n     I am Wet and ready for you.     It is not your looks but your imagination that matters most,\n     With My sexy voice I can make your dream come true...\n  \n     Hurry Up! call me let me Cummmmm for you..........................\nTOLL-FREE:             1-877-451-TEEN (1-877-451-8336)For phone billing:     1-900-993-2582\n-- \n_______________________________________________\nSign-up for your own FREE Personalized E-mail at Mail.com\nhttp://www.mail.com/?sr=signup'

In [12]:
df['Email Type'].value_counts(normalize=True)

Email Type
Safe Email        0.607078
Phishing Email    0.392922
Name: proportion, dtype: float64

In [13]:
df.dropna(inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18634 entries, 0 to 18649
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Email Text  18634 non-null  object
 1   Email Type  18634 non-null  object
dtypes: object(2)
memory usage: 436.7+ KB

In [15]:
def get_language(x):
  try:
    return detect(x)
  except:
    return "unknown"

In [16]:
df["language"]=df['Email Text'].apply(get_language)
df['language'].value_counts()

language
en         17760
fr           580
es            53
ca            43
de            36
pt            32
nl            18
tr            12
it            11
da            10
af            10
cy            10
pl             9
sv             8
no             6
unknown        5
sq             5
so             3
hr             3
vi             3
ro             3
fi             2
sk             2
sw             2
id             2
sl             2
et             2
hu             1
lv             1
Name: count, dtype: int64

In [17]:
df=df[df['language']=='en']

In [18]:
def clean_text(text: str) -> str:

    # Quitar HTML primero
    text = BeautifulSoup(text, "html.parser").get_text(separator=" ")

    # Lowercase
    text = text.lower()

    # Reemplazar URLs primero
    text = re.sub(
        r'https?://\S+|www\.\S+',
        ' url_token ',
        text
    )

    # Reemplazar emails
    text = re.sub(
        r'\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b',
        ' email_token ',
        text
    )

    # Remover números
    text = re.sub(r'\b\d+(\.\d+)?\b', ' ', text)

    # Remover caracteres no alfabéticos (pero conservar underscore)
    text = re.sub(r'[^a-z_\s]', ' ', text)

    # Normalizar espacios
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [19]:
df["clean_text"] = df["Email Text"].apply(clean_text)

In [20]:
df['Email Text'].iloc[3]

'\nHello I am your hot lil horny toy.\n    I am the one you dream About,\n    I am a very open minded person,\n    Love to talk about and any subject.\n    Fantasy is my way of life, \n    Ultimate in sex play.     Ummmmmmmmmmmmmm\n     I am Wet and ready for you.     It is not your looks but your imagination that matters most,\n     With My sexy voice I can make your dream come true...\n  \n     Hurry Up! call me let me Cummmmm for you..........................\nTOLL-FREE:             1-877-451-TEEN (1-877-451-8336)For phone billing:     1-900-993-2582\n-- \n_______________________________________________\nSign-up for your own FREE Personalized E-mail at Mail.com\nhttp://www.mail.com/?sr=signup'

In [21]:
df['clean_text'].iloc[3]

'hello i am your hot lil horny toy i am the one you dream about i am a very open minded person love to talk about and any subject fantasy is my way of life ultimate in sex play ummmmmmmmmmmmmm i am wet and ready for you it is not your looks but your imagination that matters most with my sexy voice i can make your dream come true hurry up call me let me cummmmm for you toll free teen for phone billing _______________________________________________ sign up for your own free personalized e mail at mail com url_token'

In [22]:
nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

def tokenize_and_lemmatize(text):
    doc = nlp(text)
    return [
        token.lemma_
        for token in doc
        if token.is_alpha or token.text in {"url_token", "email_token"}
    ]

In [23]:
base_path = "/content/drive/MyDrive/NLP1/model"

os.makedirs(base_path, exist_ok=True)

nlp.to_disk(base_path + "/spacy_pipeline")

In [24]:
df = df[df["clean_text"].str.len() < 50000]

In [25]:
df['tokens']=df['clean_text'].apply(tokenize_and_lemmatize)

In [26]:
df['tokens']

0        [re, disc, uniformitarianism, re, sex, lang, d...
1        [the, other, side, of, galicismos, galicismo, ...
2        [re, equistar, deal, ticket, be, you, still, a...
3        [hello, I, be, your, hot, lil, horny, toy, I, ...
4        [software, at, incredibly, low, price, low, dr...
                               ...
18644    [rick, moen, a, crit, I, m, confused, I, think...
18645    [date, a, lonely, housewife, always, want, to,...
18646    [request, submit, access, request, for, anita,...
18647    [re, important, prc, mtg, hi, dorn, john, as, ...
18648    [press, clipping, letter, on, californian, uti...
Name: tokens, Length: 17738, dtype: object

In [27]:
def get_tokens(tokens):
  cleaned_tokens = []
  for token in tokens:
    if token in NAMES: continue
    if token in STOPWORDS: continue
    if (len(token) == 1 and token.isalpha() and token not in {"a", "i"}):continue
    if pos_tag([token])[0][1][:2] not in ["NN", "VB", "JJ", "RB"] and token not in{"url_token","email_token"}: continue
    cleaned_tokens.append(token)

  return cleaned_tokens

In [28]:
df['tokens']=df['tokens'].apply(get_tokens)

In [29]:
df["text_length"] = df["clean_text"].str.len()
df.sort_values("text_length", ascending=False).head()

,Email Text,Email Type,language,clean_text,tokens,text_length
15915,enron mentions - 11 / 19 / 01 headed for a fal...,Safe Email,en,enron mentions headed for a fall companies iss...,"[enron, mention, head, fall, company, issue, s...",47572
1881,enron mentions enrononline competitor reports ...,Safe Email,en,enron mentions enrononline competitor reports ...,"[enron, mention, enrononline, competitor, repo...",47307
14274,\n---259765881.993893904265.JavaMail.RovAdmin....,Phishing Email,en,javamail rovadmin rovweb content type text pla...,"[javamail, rovadmin, rovweb, content, type, te...",46414
6073,enron mentions - 11 / 30 / 01 enron australia ...,Safe Email,en,enron mentions enron australia is barred from ...,"[enron, mention, enron, australia, bar, tradin...",46076
2099,enron mentions enron names special committee t...,Safe Email,en,enron mentions enron names special committee t...,"[enron, mention, enron, name, special, committ...",43071

In [30]:
df['tokens']

0        [disc, uniformitarianism, sex, lang, dick, hud...
1        [side, galicismos, galicismo, spanish, term, n...
2        [equistar, deal, ticket, still, available, ass...
3        [hello, hot, lil, horny, toy, dream, open, min...
4        [software, incredibly, low, price, low, draper...
                               ...
18644    [rick, moen, crit, confused, think, gpl, ed, m...
18645    [date, lonely, housewife, always, want, date, ...
18646    [request, submit, access, request, anita, dupo...
18647    [important, prc, mtg, hi, dorn, john, discover...
18648    [press, clipping, letter, californian, utility...
Name: tokens, Length: 17738, dtype: object

In [31]:
df.drop_duplicates(subset="clean_text", inplace=True)

In [32]:
full_vocabulary = []
vocabulary = {category: [] for category in df["Email Type"].unique()}
for _, row in df.iterrows():
  tokens = row["tokens"]
  sentiment = row["Email Type"]
  vocabulary[sentiment] += tokens
  full_vocabulary += tokens

In [33]:
print(f"Cantidad de tokens del vocabulario: {len(FreqDist(full_vocabulary))}")

Cantidad de tokens del vocabulario: 107014

In [34]:
FreqDist(full_vocabulary).most_common(500)

[('enron', 13977),
 ('ect', 10972),
 ('get', 10408),
 ('use', 9695),
 ('url_token', 9651),
 ('please', 9428),
 ('make', 9280),
 ('com', 9172),
 ('mail', 8706),
 ('information', 8642),
 ('company', 8433),
 ('new', 8401),
 ('email', 8184),
 ('time', 8183),
 ('list', 8150),
 ('language', 8133),
 ('send', 8120),
 ('work', 7362),
 ('say', 6414),
 ('address', 6233),
 ('report', 6175),
 ('university', 6166),
 ('know', 6125),
 ('need', 6036),
 ('business', 5920),
 ('subject', 5850),
 ('order', 5840),
 ('go', 5826),
 ('also', 5817),
 ('message', 5744),
 ('free', 5667),
 ('year', 5498),
 ('day', 5497),
 ('well', 5425),
 ('see', 5370),
 ('include', 5359),
 ('hou', 5280),
 ('people', 5136),
 ('price', 5111),
 ('receive', 5098),
 ('take', 5049),
 ('good', 5048),
 ('email_token', 5044),
 ('http', 4980),
 ('system', 4968),
 ('call', 4840),
 ('look', 4787),
 ('name', 4785),
 ('thank', 4763),
 ('want', 4593),
 ('program', 4466),
 ('service', 4426),
 ('money', 4409),
 ('find', 4328),
 ('number', 4237),
 ('write', 4089),
 ('give', 4071),
 ('paper', 4041),
 ('group', 3979),
 ('first', 3924),
 ('follow', 3822),
 ('pm', 3807),
 ('provide', 3799),
 ('change', 3775),
 ('www', 3695),
 ('way', 3660),
 ('week', 3656),
 ('think', 3653),
 ('offer', 3647),
 ('market', 3586),
 ('site', 3560),
 ('product', 3515),
 ('contact', 3435),
 ('forward', 3412),
 ('conference', 3394),
 ('click', 3363),
 ('come', 3318),
 ('software', 3301),
 ('many', 3288),
 ('deal', 3270),
 ('base', 3201),
 ('question', 3199),
 ('gas', 3182),
 ('help', 3145),
 ('file', 3102),
 ('web', 3076),
 ('issue', 3072),
 ('cc', 3061),
 ('right', 3036),
 ('available', 3008),
 ('date', 2986),
 ('internet', 2974),
 ('home', 2967),
 ('research', 2967),
 ('let', 2953),
 ('state', 2942),
 ('energy', 2941),
 ('net', 2931),
 ('fax', 2920),
 ('start', 2878),
 ('line', 2867),
 ('much', 2856),
 ('form', 2840),
 ('security', 2838),
 ('mailing', 2829),
 ('month', 2825),
 ('power', 2821),
 ('linguistic', 2814),
 ('check', 2812),
 ('th', 2790),
 ('world', 2776),
 ('word', 2749),
 ('even', 2747),
 ('long', 2710),
 ('user', 2709),
 ('last', 2705),
 ('back', 2695),
 ('stock', 2683),
 ('today', 2647),
 ('pay', 2609),
 ('book', 2601),
 ('problem', 2601),
 ('phone', 2573),
 ('next', 2556),
 ('try', 2539),
 ('risk', 2520),
 ('high', 2515),
 ('vince', 2508),
 ('result', 2492),
 ('statement', 2472),
 ('account', 2447),
 ('regard', 2439),
 ('credit', 2439),
 ('remove', 2434),
 ('term', 2407),
 ('read', 2392),
 ('place', 2387),
 ('link', 2384),
 ('case', 2377),
 ('inc', 2370),
 ('english', 2370),
 ('part', 2359),
 ('request', 2353),
 ('share', 2350),
 ('project', 2348),
 ('process', 2338),
 ('computer', 2327),
 ('set', 2322),
 ('original', 2311),
 ('plan', 2289),
 ('thing', 2274),
 ('page', 2269),
 ('future', 2264),
 ('cost', 2258),
 ('edu', 2257),
 ('point', 2253),
 ('news', 2241),
 ('note', 2206),
 ('review', 2202),
 ('copy', 2168),
 ('great', 2155),
 ('interest', 2139),
 ('de', 2135),
 ('rate', 2118),
 ('john', 2117),
 ('online', 2117),
 ('investment', 2104),
 ('run', 2100),
 ('corp', 2099),
 ('technology', 2092),
 ('end', 2086),
 ('show', 2084),
 ('office', 2065),
 ('still', 2057),
 ('datum', 2053),
 ('support', 2034),
 ('customer', 2030),
 ('position', 1996),
 ('add', 1982),
 ('sell', 1978),
 ('require', 1969),
 ('development', 1965),
 ('buy', 1948),
 ('ask', 1946),
 ('sale', 1936),
 ('linux', 1930),
 ('keep', 1917),
 ('international', 1917),
 ('workshop', 1914),
 ('special', 1903),
 ('low', 1875),
 ('text', 1873),
 ('full', 1871),
 ('hour', 1859),
 ('application', 1846),
 ('tell', 1836),
 ('type', 1834),
 ('save', 1828),
 ('complete', 1823),
 ('easy', 1816),
 ('visit', 1815),
 ('management', 1796),
 ('talk', 1788),
 ('area', 1754),
 ('update', 1747),
 ('study', 1745),
 ('late', 1737),
 ('life', 1732),
 ('move', 1728),
 ('opportunity', 1725),
 ('source', 1723),
 ('version', 1719),
 ('access', 1707),
 ('meeting', 1704),
 ('different', 1694),
 ('contract', 1692),
 ('card', 1692),
 ('fact', 1686),
 ('expect', 1684),
 ('win', 1679),
 ('example', 1677),
 ('real', 1673),
 ('current', 1668),
 ('believe', 1664),
 ('uk', 1662),
 ('large', 1660),
 ('etc', 1660),
 ('level', 1656),
 ('sure', 1654),
 ('financial', 1654),
 ('put', 1650),
 ('website', 1647),
 ('possible', 1645),
 ('member', 1641),
 ('usa', 1640),
 ('trade', 1636),
 ('hold', 1634),
 ('increase', 1632),
 ('second', 1630),
 ('spam', 1625),
 ('however', 1615),
 ('mean', 1605),
 ('due', 1602),
 ('feature', 1593),
 ('post', 1588),
 ('really', 1587),
 ('course', 1573),
 ('letter', 1563),
 ('marketing', 1557),
 ('network', 1553),
 ('mark', 1550),
 ('server', 1544),
 ('bank', 1543),
 ('seem', 1538),
 ('event', 1537),
 ('department', 1535),
 ('trading', 1522),
 ('country', 1520),
 ('release', 1519),
 ('value', 1519),
 ('detail', 1518),
 ('contain', 1516),
 ('interested', 1516),
 ('total', 1514),
 ('continue', 1510),
 ('open', 1508),
 ('discussion', 1502),
 ('create', 1500),
 ('government', 1499),
 ('session', 1495),
 ('natural', 1491),
 ('linguistics', 1478),
 ('content', 1476),
 ('cash', 1473),
 ('abstract', 1470),
 ('wish', 1464),
 ('act', 1461),
 ('never', 1454),
 ('theory', 1451),
 ('code', 1440),
 ('model', 1435),
 ('dollar', 1429),
 ('reply', 1428),
 ('general', 1426),
 ('submit', 1426),
 ('man', 1425),
 ('old', 1424),
 ('search', 1423),
 ('transaction', 1422),
 ('allow', 1422),
 ('volume', 1421),
 ('reference', 1417),
 ('present', 1416),
 ('houston', 1415),
 ('big', 1411),
 ('experience', 1407),
 ('anyone', 1407),
 ('lot', 1406),
 ('become', 1399),
 ('discuss', 1398),
 ('student', 1383),
 ('david', 1382),
 ('analysis', 1381),
 ('build', 1379),
 ('cd', 1378),
 ('less', 1373),
 ('stop', 1373),
 ('kaminski', 1373),
 ('july', 1370),
 ('learn', 1370),
 ('submission', 1370),
 ('something', 1368),
 ('family', 1367),
 ('lead', 1363),
 ('sign', 1361),
 ('non', 1360),
 ('html', 1360),
 ('option', 1360),
 ('info', 1356),
 ('far', 1353),
 ('top', 1350),
 ('center', 1346),
 ('lose', 1343),
 ('font', 1340),
 ('fund', 1329),
 ('window', 1328),
 ('size', 1325),
 ('claim', 1323),
 ('communication', 1320),
 ('package', 1318),
 ('able', 1314),
 ('minute', 1314),
 ('person', 1312),
 ('purchase', 1312),
 ('august', 1307),
 ('return', 1306),
 ('meet', 1305),
 ('friday', 1301),
 ('job', 1299),
 ('section', 1298),
 ('understand', 1298),
 ('early', 1297),
 ('leave', 1297),
 ('view', 1292),
 ('response', 1291),
 ('feel', 1287),
 ('little', 1285),
 ('attach', 1280),
 ('bill', 1279),
 ('co', 1277),
 ('least', 1275),
 ('professional', 1274),
 ('team', 1267),
 ('control', 1263),
 ('author', 1258),
 ('box', 1253),
 ('industry', 1250),
 ('grant', 1245),
 ('already', 1243),
 ('guarantee', 1242),
 ('consider', 1241),
 ('several', 1240),
 ('america', 1234),
 ('monday', 1234),
 ('idea', 1231),
 ('structure', 1229),
 ('hard', 1228),
 ('agreement', 1226),
 ('speak', 1222),
 ('involve', 1219),
 ('ever', 1217),
 ('important', 1216),
 ('mr', 1213),
 ('resource', 1211),
 ('live', 1208),
 ('fast', 1204),
 ('additional', 1202),
 ('always', 1199),
 ('small', 1197),
 ('design', 1192),
 ('subscription', 1186),
 ('hear', 1185),
 ('investor', 1184),
 ('party', 1183),
 ('schedule', 1181),
 ('school', 1181),
 ('september', 1178),
 ('performance', 1176),
 ('california', 1171),
 ('short', 1170),
 ('american', 1168),
 ('url', 1167),
 ('begin', 1166),
 ('download', 1163),
 ('register', 1161),
 ('past', 1159),
 ('bring', 1158),
 ('develop', 1157),
 ('fee', 1145),
 ('accept', 1144),
 ('speaker', 1142),
 ('president', 1140),
 ('soon', 1140),
 ('thousand', 1139),
 ('registration', 1139),
 ('currently', 1137),
 ('method', 1137),
 ('speech', 1137),
 ('sponsor', 1136),
 ('comment', 1128),
 ('rpm', 1126),
 ('individual', 1122),
 ('title', 1116),
 ('break', 1112),
 ('operation', 1112),
 ('committee', 1111),
 ('relate', 1109),
 ('press', 1108),
 ('error', 1108),
 ('drive', 1106),
 ('action', 1106),
 ('material', 1106),
 ('approach', 1106),
 ('apply', 1097),
 ('st', 1092),
 ('payment', 1091),
 ('louise', 1084),
 ('science', 1078),
 ('select', 1078),
 ('legal', 1069),
 ('answer', 1068),
 ('charge', 1067),
 ('june', 1061),
 ('reason', 1061),
 ('anything', 1057),
 ('major', 1057),
 ('notice', 1056),
 ('close', 1055),
 ('presentation', 1055),
 ('personal', 1054),
 ('acquisition', 1047),
 ('concern', 1047),
 ('standard', 1047),
 ('march', 1043),
 ('friend', 1043),
 ('amount', 1037),
 ('someone', 1036),
 ('kind', 1034),
 ('unsubscribe', 1030),
 ('field', 1026),
 ('topic', 1020),
 ('focus', 1019),
 ('decide', 1018),
 ('april', 1017),
 ('york', 1016),
 ('simple', 1016),
 ('step', 1015),
 ('database', 1011),
 ('grammar', 1006),
 ('test', 1004),
 ('razor', 1004),
 ('semantic', 1001),
 ('join', 999),
 ('global', 998),
 ('director', 997),
 ('happen', 996),
 ('enter', 994),
 ('city', 990),
 ('microsoft', 985),
 ('quality', 983),
 ('tool', 983),
 ('yet', 980),
 ('public', 975),
 ('document', 975),
 ('october', 975),
 ('watch', 974),
 ('key', 972),
 ('mention', 967),
 ('remember', 967),
 ('dr', 967),
 ('simply', 965),
 ('recent', 963),
 ('cause', 963),
 ('fall', 963),
 ('north', 959),
 ('ac', 959),
 ('hi', 959),
 ('adobe', 959),
 ('hand', 956),
 ('asset', 955),
 ('direct', 954),
 ('invite', 952),
 ('record', 952),
 ('rule', 951),
 ('wednesday', 950),
 ('transfer', 945),
 ('hope', 944),
 ('thursday', 943),
 ('final', 942),
 ('yes', 938)]

In [35]:
#Guardamos los archivos necesarios
#with open('/content/drive/MyDrive/NLP1/lemmatizer.pkl', 'wb') as f:
    #pickle.dump(lemmatizer,f)

In [36]:
df['tokens'].iloc[3]

['hello',
 'hot',
 'lil',
 'horny',
 'toy',
 'dream',
 'open',
 'minded',
 'person',
 'love',
 'talk',
 'subject',
 'fantasy',
 'way',
 'life',
 'ultimate',
 'sex',
 'play',
 'ummmmmmmmmmmmmm',
 'wet',
 'ready',
 'look',
 'imagination',
 'matter',
 'sexy',
 'voice',
 'make',
 'dream',
 'come',
 'true',
 'hurry',
 'call',
 'let',
 'cummmmm',
 'toll',
 'free',
 'teen',
 'phone',
 'billing',
 'sign',
 'free',
 'personalize',
 'mail',
 'mail',
 'com',
 'url_token']

In [37]:
most_common_tokens = set()
for category in df["Email Type"].unique():
  most_common_tokens = most_common_tokens.union(set([token for token, _ in FreqDist(vocabulary[category]).most_common(500)]))
most_common_tokens

{'able',
 'abstract',
 'ac',
 'accept',
 'access',
 'account',
 'acquisition',
 'act',
 'action',
 'actually',
 'ad',
 'add',
 'additional',
 'address',
 'adobe',
 'adult',
 'advertisement',
 'advertising',
 'advice',
 'age',
 'agent',
 'agree',
 'agreement',
 'allow',
 'already',
 'also',
 'always',
 'america',
 'american',
 'amount',
 'analysis',
 'analyst',
 'announce',
 'answer',
 'anticipate',
 'anyone',
 'anything',
 'appear',
 'application',
 'apply',
 'approach',
 'approve',
 'april',
 'area',
 'article',
 'ask',
 'aspect',
 'asset',
 'assistance',
 'associate',
 'attach',
 'august',
 'author',
 'available',
 'away',
 'back',
 'bank',
 'base',
 'become',
 'begin',
 'believe',
 'benefit',
 'big',
 'bill',
 'bit',
 'body',
 'bonus',
 'book',
 'box',
 'br',
 'brand',
 'break',
 'bring',
 'build',
 'bulk',
 'business',
 'buy',
 'california',
 'call',
 'canada',
 'capacity',
 'card',
 'case',
 'cash',
 'cause',
 'cc',
 'cd',
 'center',
 'chair',
 'change',
 'charge',
 'check',
 'china',
 'choose',
 'city',
 'claim',
 'click',
 'close',
 'co',
 'code',
 'color',
 'com',
 'come',
 'comment',
 'committee',
 'communication',
 'company',
 'complete',
 'computer',
 'concern',
 'conference',
 'consider',
 'contact',
 'contain',
 'content',
 'continue',
 'contract',
 'control',
 'copy',
 'copyright',
 'corp',
 'corporation',
 'cost',
 'country',
 'course',
 'cover',
 'create',
 'credit',
 'current',
 'currently',
 'customer',
 'daily',
 'database',
 'date',
 'datum',
 'david',
 'day',
 'de',
 'deadline',
 'deal',
 'dear',
 'debt',
 'december',
 'decide',
 'department',
 'deposit',
 'design',
 'detail',
 'develop',
 'development',
 'different',
 'direct',
 'director',
 'directory',
 'discount',
 'discourse',
 'discover',
 'discuss',
 'discussion',
 'document',
 'dollar',
 'domain',
 'download',
 'dr',
 'draw',
 'drive',
 'drug',
 'due',
 'dynegy',
 'early',
 'earn',
 'easy',
 'ect',
 'ed',
 'edu',
 'effort',
 'electronic',
 'email',
 'email_token',
 'employee',
 'ena',
 'end',
 'energy',
 'engine',
 'english',
 'enron',
 'enter',
 'error',
 'estimate',
 'et',
 'etc',
 'european',
 'even',
 'event',
 'ever',
 'everything',
 'example',
 'exchange',
 'exist',
 'expect',
 'expectation',
 'experience',
 'express',
 'face',
 'fact',
 'factor',
 'fall',
 'family',
 'far',
 'fast',
 'fax',
 'feature',
 'federal',
 'fee',
 'feel',
 'field',
 'file',
 'fill',
 'final',
 'financial',
 'find',
 'first',
 'focus',
 'follow',
 'font',
 'foreign',
 'form',
 'forward',
 'free',
 'friday',
 'friend',
 'full',
 'fund',
 'future',
 'fw',
 'gain',
 'gas',
 'general',
 'generate',
 'get',
 'give',
 'global',
 'go',
 'good',
 'government',
 'grammar',
 'grant',
 'great',
 'group',
 'grow',
 'growth',
 'guarantee',
 'guide',
 'hand',
 'happen',
 'hard',
 'head',
 'health',
 'hear',
 'hello',
 'help',
 'hi',
 'high',
 'hold',
 'home',
 'hope',
 'hot',
 'hou',
 'hour',
 'houston',
 'however',
 'hpl',
 'html',
 'http',
 'huge',
 'human',
 'hundred',
 'idea',
 'immediately',
 'important',
 'inc',
 'include',
 'income',
 'increase',
 'individual',
 'industry',
 'info',
 'information',
 'institute',
 'instruction',
 'intend',
 'interest',
 'interested',
 'international',
 'internet',
 'interview',
 'invest',
 'investment',
 'investor',
 'invite',
 'involve',
 'irish',
 'issue',
 'january',
 'job',
 'john',
 'join',
 'jones',
 'july',
 'june',
 'kaminski',
 'keep',
 'key',
 'kind',
 'know',
 'knowledge',
 'language',
 'large',
 'last',
 'late',
 'later',
 'law',
 'lead',
 'learn',
 'least',
 'leave',
 'legal',
 'less',
 'let',
 'letter',
 'level',
 'life',
 'limited',
 'line',
 'linguist',
 'linguistic',
 'linguistics',
 'link',
 'linux',
 'list',
 'little',
 'live',
 'loan',
 'logo',
 'london',
 'long',
 'look',
 'lose',
 'lot',
 'lottery',
 'louise',
 'love',
 'low',
 'machine',
 'mail',
 'mailing',
 'maintainer',
 'major',
 'make',
 'man',
 'manage',
 'management',
 'many',
 'march',
 'mark',
 'market',
 'marketing',
 'material',
 'matter',
 'mean',
 'medication',
 'meet',
 'meeting',
 'member',
 'membership',
 'mention',
 'message',
 'meter',
 'method',
 'michael',
 'microsoft',
 'mike',
 'mind',
 'minute',
 'mmbtu',
 'mobile',
 'model',
 'monday',
 'money',
 'month',
 'mortgage',
 'move',
 'mr',
 'ms',
 'much',
 'multi',
 'name',
 'natural',
 'nbsp',
 'necessary',
 'need',
 'net',
 'network',
 'never',
 'new',
 'news',
 'newsletter',
 'next',
 'non',
 'north',
 'note',
 'nothing',
 'notice',
 'november',
 'number',
 'october',
 'offer',
 'office',
 'oil',
 'old',
 'online',
 'oo',
 'open',
 'operation',
 'opportunity',
 'opt',
 'option',
 'order',
 'original',
 'package',
 'page',
 'paper',
 'part',
 'participant',
 'partner',
 'party',
 'pass',
 'past',
 'pay',
 'payment',
 'pc',
 'people',
 'performance',
 'person',
 'personal',
 'phone',
 'php',
 'pill',
 'place',
 'plan',
 'please',
 'pm',
 'point',
 'position',
 'possible',
 'post',
 'potential',
 'power',
 'prescription',
 'present',
 'presentation',
 'president',
 'press',
 'price',
 'private',
 'pro',
 'probably',
 'problem',
 'process',
 'produce',
 'product',
 'professional',
 'profit',
 'program',
 'project',
 'proposal',
 'prove',
 'provide',
 'public',
 'publish',
 'purchase',
 'put',
 'quality',
 'question',
 'quick',
 'rate',
 'rather',
 'razor',
 'reach',
 'read',
 'reader',
 'ready',
 'real',
 'really',
 'reason',
 'receive',
 'recent',
 'record',
 'reference',
 'regard',
 'register',
 'registration',
 'relate',
 'release',
 'remember',
 'remove',
 'reply',
 'report',
 'request',
 'require',
 'research',
 'reserve',
 'resource',
 'response',
 'result',
 'return',
 'revenue',
 'review',
 'right',
 'risk',
 'robert',
 'role',
 'room',
 'rpm',
 'rule',
 'run',
 'safe',
 'sale',
 'save',
 'say',
 'schedule',
 'school',
 'science',
 'search',
 'second',
 'secret',
 'section',
 'secure',
 'security',
 'see',
 'seek',
 'seem',
 'select',
 'sell',
 'semantic',
 'send',
 'september',
 'server',
 'service',
 'session',
 'set',
 'several',
 'sex',
 'share',
 'ship',
 'shipping',
 'short',
 'show',
 'sign',
 'simple',
 'simply',
 'site',
 'size',
 'small',
 'soft',
 'software',
 'solution',
 'someone',
 'something',
 'soon',
 'sound',
 'source',
 'spam',
 'spamassassin',
 'speak',
 'speaker',
 'special',
 'specific',
 'speech',
 'sponsor',
 'st',
 'standard',
 'start',
 'state',
 'statement',
 'states',
 'step',
 'steve',
 'still',
 'stock',
 'stop',
 'store',
 'structure',
 'student',
 'study',
 'subject',
 'submission',
 'submit',
 'subscriber',
 'subscription',
 'success',
 'successful',
 'suggest',
 'suite',
 'sum',
 'summary',
 'support',
 'sure',
 'syntax',
 'system',
 'take',
 'talk',
 'target',
 'td',
 'team',
 'technology',
 'tel',
 'tell',
 'term',
 'test',
 'texas',
 'text',
 'th',
 'thank',
 'theory',
 'thing',
 'think',
 'third',
 'thousand',
 'thursday',
 'time',
 'title',
 'today',
 'together',
 'tool',
 'top',
 'topic',
 'total',
 'trade',
 'trading',
 'transaction',
 'transfer',
 'translation',
 'try',
 'tuesday',
 'turn',
 'type',
 'uk',
 'un',
 'understand',
 'unit',
 'united',
 'university',
 'unsubscribe',
 'update',
 'url',
 'url_token',
 'usa',
 'use',
 'user',
 'value',
 'version',
 'viagra',
 'video',
 'view',
 'vince',
 'visit',
 'volume',
 'wait',
 'want',
 'watch',
 'way',
 'web',
 'website',
 'wednesday',
 'week',
 'weight',
 'welcome',
 'well',
 'win',
 'window',
 'wish',
 'woman',
 'word',
 'work',
 'workshop',
 'world',
 'worldwide',
 'write',
 'www',
 'xp',
 'year',
 'yes',
 'yet',
 'york'}

In [38]:
print(f"Cantidad de tokens comunes: {len(most_common_tokens)}")

Cantidad de tokens comunes: 695

In [39]:
# Guardar los archivos necesarios para preprocesar texto
with open("/content/drive/MyDrive/NLP1/most_common_tokens.pkl", "wb") as f:
  pickle.dump(most_common_tokens, f)

In [40]:
def get_tokens_training(email,most_common_tokens,simplifier_func=None):
  tokens = tokenize_and_lemmatize(email)
  cleaned_tokens = []
  for token in tokens:
    if not token.isalpha(): continue
    if token in NAMES: continue
    token = token.lower()
    if token in STOPWORDS: continue
    if pos_tag([token])[0][1][:2] not in ["NN", "VB", "JJ", "RB"] and token not in{"url_token","email_token"} : continue
    if simplifier_func: token = simplifier_func(token)
    if token not in most_common_tokens: continue
    cleaned_tokens.append(token)

  return " ".join(cleaned_tokens)

In [41]:
df['tokens training']=df['Email Text'].apply(lambda x:get_tokens_training(x,most_common_tokens))

#Vecorizacion

In [42]:
#Aquí desarrollamos el método Binary Term Frequency
vectorizer_binary = CountVectorizer(binary=True)
vectorizer_binary.fit(df["tokens training"])

CountVectorizer(binary=True)

In [43]:
X_binary = pd.DataFrame(
    vectorizer_binary.transform(df["tokens training"]).toarray(),
    columns=vectorizer_binary.get_feature_names_out(),
    index=df.index
)
X_binary

,able,abstract,ac,accept,access,account,acquisition,act,action,actually,...,workshop,world,worldwide,write,www,xp,year,yes,yet,york
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18644,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
18645,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
18646,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
18647,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18648,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
with open("/content/drive/MyDrive/NLP1/vectorizer_binary.pkl", "wb") as f:
  pickle.dump(vectorizer_binary, f)

In [45]:
#Aquí desarrollamos el método Bag of Words (BoW)
vectorizer_bow = CountVectorizer()
vectorizer_bow.fit(df["tokens training"])

CountVectorizer()

In [46]:
X_bow = pd.DataFrame(
    vectorizer_bow.transform(df["tokens training"]).toarray(),
    columns=vectorizer_bow.get_feature_names_out(),
    index=df.index
)
X_bow

,able,abstract,ac,accept,access,account,acquisition,act,action,actually,...,workshop,world,worldwide,write,www,xp,year,yes,yet,york
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18644,0,0,0,0,0,0,0,0,0,2,...,0,0,0,1,0,0,0,2,0,0
18645,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
18646,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
18647,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18648,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
with open("/content/drive/MyDrive/NLP1/vectorizer_bow.pkl", "wb") as f:
  pickle.dump(vectorizer_bow, f)

In [48]:
# Aquí desarrollamos el método más efectivo, el TF-IDF (Term Frequency-Inverse Document Frequency)
vectorizer_tfidf = TfidfVectorizer()
vectorizer_tfidf.fit(df["tokens training"])

TfidfVectorizer()

In [49]:
X_tf = pd.DataFrame(
    vectorizer_tfidf.transform(df["tokens training"]).toarray(),
    columns=vectorizer_tfidf.get_feature_names_out(),
    index=df.index
)
X_tf

,able,abstract,ac,accept,access,account,acquisition,act,action,actually,...,workshop,world,worldwide,write,www,xp,year,yes,yet,york
0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.206089,0.0,0.0
1,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0
2,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0
3,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0
4,0.18517,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.138945,0.00000,0.0,0.0,0.211332,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18644,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.122841,...,0.0,0.0,0.0,0.041395,0.00000,0.0,0.0,0.125922,0.0,0.0
18645,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.25395,0.0,0.0,0.000000,0.0,0.0
18646,0.00000,0.0,0.0,0.0,0.128267,0.0,0.0,0.133399,0.0,0.000000,...,0.0,0.0,0.0,0.094381,0.00000,0.0,0.0,0.000000,0.0,0.0
18647,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0
18648,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0

In [50]:
with open("/content/drive/MyDrive/NLP1/vectorizer_tfidf.pkl", "wb") as f:
  pickle.dump(vectorizer_tfidf, f)

In [60]:
Y=df['Email Type']
X_text=df['tokens training']

In [55]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizadores = {
    "BoW": CountVectorizer(),
    "Binary": CountVectorizer(binary=True),
    "TF-IDF": TfidfVectorizer()
}

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB

modelos = {
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "Random Forest": RandomForestClassifier(n_estimators=100, class_weight="balanced", random_state=42),
    "MultinomialNB": MultinomialNB()
}

In [57]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer, f1_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


f1_phishing = make_scorer(
    f1_score,
    pos_label="Phishing Email"
)

In [52]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [61]:
results = []

for vec_name, vectorizer in vectorizadores.items():

    for model_name, model in modelos.items():

        pipeline = Pipeline([
            ("vectorizer", vectorizer),
            ("classifier", model)
        ])

        scores = cross_val_score(
            pipeline,
            X_text,
            Y,
            cv=cv,
            scoring=f1_phishing
        )

        results.append({
            "Vectorizacion": vec_name,
            "Modelo": model_name,
            "CV F1 Mean": scores.mean(),
            "CV F1 Std": scores.std()
        })

results_df = pd.DataFrame(results).sort_values(
    by="CV F1 Mean",
    ascending=False
)

print(results_df)

  Vectorizacion               Modelo  CV F1 Mean  CV F1 Std
7        TF-IDF        Random Forest    0.945636   0.002639
4        Binary        Random Forest    0.945554   0.004042
1           BoW        Random Forest    0.945479   0.003361
6        TF-IDF  Logistic Regression    0.942385   0.003211
3        Binary  Logistic Regression    0.941744   0.005059
0           BoW  Logistic Regression    0.936258   0.005936
8        TF-IDF        MultinomialNB    0.924409   0.002064
5        Binary        MultinomialNB    0.917814   0.004418
2           BoW        MultinomialNB    0.904000   0.002585

In [64]:
best_pipeline = Pipeline([
    ("vectorizer", TfidfVectorizer()),
    ("classifier", LogisticRegression(class_weight="balanced"))
])

X_train, X_test, y_train, y_test = train_test_split(
    X_text,
    Y,
    test_size=0.2,
    stratify=Y,
    random_state=42
)

best_pipeline.fit(X_train, y_train)

y_pred = best_pipeline.predict(X_test)

In [65]:
best_pipeline.fit(X_train, y_train)

# Predicciones en train
y_train_pred = best_pipeline.predict(X_train)

# Predicciones en test
y_test_pred = best_pipeline.predict(X_test)

from sklearn.metrics import classification_report

print("===== TRAIN =====")
print(classification_report(y_train, y_train_pred))

print("===== TEST =====")
print(classification_report(y_test, y_test_pred))

===== TRAIN =====
                precision    recall  f1-score   support

Phishing Email       0.93      0.97      0.95      4994
    Safe Email       0.98      0.96      0.97      8426

      accuracy                           0.96     13420
     macro avg       0.96      0.96      0.96     13420
  weighted avg       0.96      0.96      0.96     13420

===== TEST =====
                precision    recall  f1-score   support

Phishing Email       0.93      0.96      0.95      1248
    Safe Email       0.98      0.96      0.97      2107

      accuracy                           0.96      3355
     macro avg       0.95      0.96      0.96      3355
  weighted avg       0.96      0.96      0.96      3355

In [54]:
df['Email Type'].value_counts()

Email Type
Safe Email        10533
Phishing Email     6242
Name: count, dtype: int64

In [68]:
import joblib

best_pipeline.fit(X_train, y_train)

joblib.dump(best_pipeline, "/content/drive/MyDrive/NLP1/phishing_model.pkl")

['/content/drive/MyDrive/NLP1/phishing_model.pkl']

In [69]:
import os
os.getcwd()

'/content'

In [70]:
MODEL_PATH = "/content/drive/MyDrive/NLP1/phishing_model.pkl"

joblib.dump(best_pipeline, MODEL_PATH)

['/content/drive/MyDrive/NLP1/phishing_model.pkl']